name: Curate News

on:
  schedule:
    - cron: '0 9 * * 1-5'
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  curate-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3
