name: Curate Cybersecurity News

on:
  schedule:
    - cron: '0 6 * * *' # Runs at 6 AM daily
  workflow_dispatch:

jobs:
  curate-news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Updated to v4 which uses Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4 # Specify the latest version explicitly
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml

    - name: Run curator script
      run: |
        python curator.py
